### ISSUE TITLE
Error running esy build

### ISSUE THREAD

**Issue by dylanirlbeck** [jchavarri/hello-ppx-esy#2]
Hello! I'm trying to run the command ```esy build``` as specified in the README, and I'm getting the following error:

```
info esy build 0.5.8 (using package.json)
File "example-native/dune", line 1, characters 0-84:
1 | (executable
2 |   (name Hello)
3 |   (public_name Hello.exe)
4 |   (preprocess (pps test_ppx))
5 | )
Error: The current project defines some public elements, but no opam packages
are defined.
Please add a <package>.opam file at the project root so that these elements
are installed into it.
error: command failed: 'refmterr' 'dune' 'build' '-p' 'test_ppx' (exited with 1)
esy-build-package: exiting with errors above...
error: build failed with exit code: 1
  
esy: exiting due to errors above
```

Any ideas on how to fix it? Note that I'm quite new to Reason so I apologize for an inconvenience. I'm attempting to learn how to write a PPX 😄 .

Thanks in advance!

**Comment by jchavarri** [comment]
@dylanirlbeck Thanks for reporting!

I added a setup + some instructions in #3. Docs are here: https://github.com/jchavarri/hello-ppx-esy/tree/master/example-native

Please feel free to create a new issue if you find anything missing or failing :)
